### ISSUE TITLE
Improvement to Deploy

### ISSUE THREAD

**Issue by dbpolito** [firework/deployer#15]
### Tasks

- [x] 1. Blank Option to Server and Branch selects
- [x] 2. Confirm Modal before go
- [x] 3. Redirect to deploy page (specific, only that deploy)
- [x] 4. Add column `user_id` and track what user triggered the deploy
- [x] 5. Add column `finished_at` and track when the deploy finished to run (when you change status to complete)
- [x] 6. Separate Outputs By Server (maybe use tabs)
- [x] 7. Only show first and last line of the deploy on the Deploy Grid
- [x] 8. Deploy Detail Page (Can be a separated page or a modal)
- [x] 9. Improve how status are shown, with colours, etc, also fix status typo on `status ENUM column`
