### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by dbpolito** [firework/deployer#4]
### Tasks

- [x] 1. Change from `Session` to `Cache`, file driver is fine
- [x] 2. Add `path` on connection config so you can go to the right path for each project
- [x] 3. Send Model to Job
- [x] 4. Move deploy_command file to storage folder
- [x] 5. Remove id_rsa
